In [1]:
import pandas as pd

In [2]:
#Reading csv file from url
df = pd.read_csv('http://13.234.66.67/summer19/datasets/info.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
X = df.iloc[:,0:].values
X

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, nan, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', nan, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [4]:
#removing  missing values or replacing missing value with some relavant data
#df.describe()
from sklearn.preprocessing import Imputer


In [5]:
imp=Imputer(missing_values='NaN',axis=0,strategy='mean')

c:\users\rudresh\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [6]:
impute = imp.fit(X[:,1:3]) #this is only fitting of columns that we want to process

In [7]:
#time for transforming the fitted columns
impute.transform(X[:,1:3])

array([[4.40000000e+01, 7.20000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.00000000e+01, 5.40000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.00000000e+01, 6.37777778e+04],
       [3.50000000e+01, 5.80000000e+04],
       [3.87777778e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [3.70000000e+01, 6.70000000e+04]])

In [8]:
X

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, nan, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', nan, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [9]:
#string label int/float
from sklearn.preprocessing import LabelEncoder

In [10]:
cont = LabelEncoder() #this is country labeling

In [11]:
#now apply column first in labelEn
X[:,0] = cont.fit_transform(X[:,0])

In [12]:
X

array([[0, 44.0, 72000.0, 'No'],
       [2, 27.0, 48000.0, 'Yes'],
       [1, 30.0, 54000.0, 'No'],
       [2, 38.0, 61000.0, 'No'],
       [1, 40.0, nan, 'Yes'],
       [0, 35.0, 58000.0, 'Yes'],
       [2, nan, 52000.0, 'No'],
       [0, 48.0, 79000.0, 'Yes'],
       [1, 50.0, 83000.0, 'No'],
       [0, 37.0, 67000.0, 'Yes']], dtype=object)

In [13]:
p = LabelEncoder()

In [14]:
X[:,3] = p.fit_transform(X[:,3])

In [15]:
X

array([[0, 44.0, 72000.0, 0],
       [2, 27.0, 48000.0, 1],
       [1, 30.0, 54000.0, 0],
       [2, 38.0, 61000.0, 0],
       [1, 40.0, nan, 1],
       [0, 35.0, 58000.0, 1],
       [2, nan, 52000.0, 0],
       [0, 48.0, 79000.0, 1],
       [1, 50.0, 83000.0, 0],
       [0, 37.0, 67000.0, 1]], dtype=object)

In [16]:
#now encoding first column 
from sklearn.preprocessing import OneHotEncoder

In [17]:
firstcl = OneHotEncoder(categorical_features=[0]) #define exacr column number where we want to make category


In [18]:
X = firstcl.fit_transform(X)
#after transformation we neeed to convert into numpy array

c:\users\rudresh\appdata\local\programs\python\python37\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [19]:
X.astype(int) #to show in int only

ValueError: cannot convert float NaN to integer